import { randomUUID } from "node:crypto";

import { analyze } from "./analyze.js";
import { walkCascade } from "./cascade.js";
import {
  assertTypeName,
  columnTypes,
  labelColumn,
  primaryKeyColumns,
  qualify,
  quoteIdent,
  type Relation,
  resolveRelation,
} from "./catalog.js";
import {
  afterAlias,
  beforeAlias,
  deriveCount,
  deriveRead,
  keyAlias,
  LABEL_ALIAS,
  VERSION_ALIAS,
} from "./derive.js";
import type { Driver, Row, Sql } from "./driver.js";
import {
  PgPreviewError,
  ProposalExpiredError,
  StateChangedError,
  TooManyRowsError,
} from "./errors.js";
import { buildInsertApply, previewInsert } from "./insert.js";
import { required } from "./invariant.js";
import { postgresDriver } from "./postgres-driver.js";
import { optionalText } from "./row.js";
import type {
  DriftedRow,
  FieldChange,
  Proposal,
  Receipt,
  RowChange,
} from "./types.js";
import { mutationWarnings } from "./warnings.js";

export interface PreviewerOptions {
  /**
   * Connection string. Used for previews and for applies.
   *
   * One URL is enough. The derived read is generated by this library, never by
   * a caller or a model, and the statement is refused unless it is an UPDATE or
   * DELETE the rewriter fully understands, so the rewriter cannot emit a write.
   * Previews additionally run inside `BEGIN TRANSACTION READ ONLY`, which is
   * what stops a predicate that calls a volatile `SECURITY DEFINER` function
   * from writing.
   */
  readonly url?: string;
  /**
   * Optional least-privilege upgrade: a `SELECT`-only connection string used
   * for previews. Recommended, never required. With it, write-incapability
   * during preview is enforced by PostgreSQL privileges rather than by this
   * library being correct.
   */
  readonly readUrl?: string;
  /** Supply your own pool or a non-server Postgres. Replaces `url`. */
  readonly driver?: Driver;
  /** Supply your own read-only pool. Replaces `readUrl`. */
  readonly readDriver?: Driver;
  /**
   * Largest number of rows a single proposal may name. Default 1000.
   *
   * An approval names its rows, so the apply carries one tuple per row. Past
   * this point the change is not a decision a human can review and belongs in a
   * reviewed migration.
   */
  readonly maxRows?: number;
  /** How long a proposal stays applicable. Default 5 minutes. */
  readonly ttlMs?: number;
  /** Per-statement timeout for previews and applies. Default 10s. */
  readonly statementTimeoutMs?: number;
  /** Candidate human-recognisable columns, in priority order. */
  readonly labelColumns?: readonly string[];
  /** How deep to follow `ON DELETE CASCADE`. Default 5. */
  readonly cascadeDepth?: number;
  /** Injectable clock, for tests. */
  readonly now?: () => Date;
}

export interface Previewer {
  /** Derive a read-only preview of what `statement` would change. */
  propose(statement: string, params?: readonly unknown[]): Promise<Proposal>;
  /** Apply exactly the rows in `proposal`, only if none of them have changed. */
  apply(proposal: Proposal): Promise<Receipt>;
  close(): Promise<void>;
}

const DEFAULT_LABELS = [
  "email",
  "name",
  "slug",
  "title",
  "label",
  "username",
  "handle",
] as const;

const CASCADE_KEYS_PER_LEVEL = 5_000;

/**
 * Separator for composite row identities. Written as an escape rather than a
 * literal NUL so this file stays text: a literal one makes git treat the whole
 * source as binary, and the diff of the most important file in the package
 * becomes unreviewable.
 */
const NUL = "\u0000";

export function createPreviewer(options: PreviewerOptions): Previewer {
  const ownedDrivers: Driver[] = [];

  let writeDriver = options.driver;
  if (!writeDriver) {
    if (options.url === undefined) {
      throw new PgPreviewError(
        "createPreviewer needs either a `url` or a `driver`.",
      );
    }
    writeDriver = postgresDriver(options.url);
    ownedDrivers.push(writeDriver);
  }

  let readDriver = options.readDriver;
  if (!readDriver) {
    if (options.readUrl === undefined) {
      readDriver = writeDriver;
    } else {
      readDriver = postgresDriver(options.readUrl);
      ownedDrivers.push(readDriver);
    }
  }

  const write = writeDriver;
  const read = readDriver;
  const maxRows = options.maxRows ?? 1_000;
  const ttlMs = options.ttlMs ?? 5 * 60_000;
  const timeoutMs = Math.trunc(options.statementTimeoutMs ?? 10_000);
  const labels = options.labelColumns ?? DEFAULT_LABELS;
  const cascadeDepth = options.cascadeDepth ?? 5;
  const clock = options.now ?? ((): Date => new Date());

  return {
    async propose(statement, params = []) {
      const analysis = await analyze(statement);

      return await read.session(async (sql) => {
        await sql("BEGIN TRANSACTION READ ONLY");
        try {
          await sql(`SET LOCAL statement_timeout = ${timeoutMs}`);

          const relation = await resolveRelation(
            sql,
            analysis.schema,
            analysis.table,
          );

          if (analysis.kind === "insert") {
            const preview = await previewInsert(sql, analysis, {
              relation,
              params,
              labelColumns: labels,
              maxRows,
            });
            return {
              ...identity(clock(), ttlMs),
              kind: "insert",
              table: relation.ref,
              rowCount: preview.changes.length,
              changes: preview.changes,
              // An insert reaches no further than the row it creates: a foreign
              // key constrains it rather than carrying it anywhere.
              cascades: [],
              warnings: preview.warnings,
              derivedSql: preview.derivedSql,
              plan: preview.plan,
            } satisfies Proposal;
          }

          const keyColumns = await primaryKeyColumns(sql, relation);
          const types = await columnTypes(sql, relation);
          const label = await labelColumn(sql, relation, labels);

          const derived = await deriveRead({
            analysis,
            keyColumns,
            labelColumn: label,
            columnTypes: types,
            limit: maxRows + 1,
          });

          const rows = await sql(derived.sql, params);
          if (rows.length > maxRows) {
            const counted = await sql(await deriveCount(analysis), params);
            const exact = Number(counted[0]?.["n"] ?? rows.length);
            throw new TooManyRowsError(exact, maxRows);
          }

          const changes = rows.map((row) =>
            toRowChange(row, keyColumns, derived.assignedColumns, label),
          );

          const warnings = await mutationWarnings(
            sql,
            relation,
            analysis.kind,
            derived.assignedColumns,
          );

          const cascade =
            analysis.kind === "delete"
              ? await walkCascade(
                  sql,
                  relation,
                  rootValues(sql, relation, keyColumns, changes),
                  {
                    maxDepth: cascadeDepth,
                    maxKeysPerLevel: CASCADE_KEYS_PER_LEVEL,
                  },
                )
              : { nodes: [], warnings: [] };

          return {
            ...identity(clock(), ttlMs),
            kind: analysis.kind,
            table: relation.ref,
            rowCount: changes.length,
            changes,
            cascades: cascade.nodes,
            warnings: [...warnings, ...cascade.warnings],
            derivedSql: derived.sql,
            plan: {
              keyColumns,
              assignments: derived.assignedColumns.map((column) => ({
                column,
                type: required(types.get(column), `type of ${column}`),
              })),
            },
          } satisfies Proposal;
        } finally {
          await rollbackQuietly(sql);
        }
      });
    },

    async apply(proposal) {
      const now = clock();
      if (Date.parse(proposal.expiresAt) <= now.getTime()) {
        throw new ProposalExpiredError(proposal.id, proposal.expiresAt);
      }
      if (proposal.rowCount === 0) {
        return {
          proposalId: proposal.id,
          rowsAffected: 0,
          appliedAt: now.toISOString(),
          keys: [],
        };
      }

      return await write.session(async (sql) => {
        await sql("BEGIN");
        try {
          await sql(`SET LOCAL statement_timeout = ${timeoutMs}`);

          const statement =
            proposal.kind === "insert"
              ? buildInsertApply(proposal)
              : buildApply(proposal);
          const returned = await sql(statement.text, statement.params);

          if (returned.length !== proposal.changes.length) {
            // An insert names no existing row, so a short count is not drift:
            // the rows it was told to write are the rows it wrote, or it threw.
            if (proposal.kind === "insert") {
              throw new PgPreviewError(
                `Insert wrote ${returned.length} of ${proposal.changes.length} ` +
                  `previewed row(s). Nothing was applied.`,
              );
            }
            throw new StateChangedError(
              proposal.id,
              await findDrift(sql, proposal, returned),
            );
          }

          await sql("COMMIT");
          return {
            proposalId: proposal.id,
            rowsAffected: returned.length,
            appliedAt: clock().toISOString(),
            keys: returnedKeys(proposal.plan.keyColumns, returned),
          };
        } catch (error) {
          await rollbackQuietly(sql);
          throw error;
        }
      });
    },

    async close() {
      await Promise.all(
        ownedDrivers.map(async (driver) => await driver.close()),
      );
    },
  };
}

/** Identity and lifetime, the same for every kind of proposal. */
function identity(
  createdAt: Date,
  ttlMs: number,
): Pick<Proposal, "id" | "createdAt" | "expiresAt"> {
  return {
    id: `prp_${randomUUID().replaceAll("-", "").slice(0, 16)}`,
    createdAt: createdAt.toISOString(),
    expiresAt: new Date(createdAt.getTime() + ttlMs).toISOString(),
  };
}

/** The keys the apply returned, as the receipt reports them. */
function returnedKeys(
  keyColumns: readonly string[],
  returned: readonly Row[],
): readonly Readonly<Record<string, string>>[] {
  if (keyColumns.length === 0) return [];
  return returned.map((row) =>
    Object.fromEntries(
      keyColumns.map((column, i) => [column, String(row[keyAlias(i)])]),
    ),
  );
}

/**
 * A rollback that cannot mask the error that caused it. The session is released
 * immediately afterwards, so a failed rollback has nothing left to corrupt.
 */
async function rollbackQuietly(sql: Sql): Promise<void> {
  try {
    await sql("ROLLBACK");
  } catch {
    // deliberately ignored
  }
}

function toRowChange(
  row: Row,
  keyColumns: readonly string[],
  assigned: readonly string[],
  label: string | undefined,
): RowChange {
  const key: Record<string, string> = {};
  keyColumns.forEach((column, i) => {
    key[column] = String(row[keyAlias(i)]);
  });

  const fields: FieldChange[] = assigned.map((column, i) => ({
    column,
    before: optionalText(row, beforeAlias(i)),
    after: optionalText(row, afterAlias(i)),
  }));

  return {
    key,
    version: String(row[VERSION_ALIAS]),
    label: label === undefined ? null : optionalText(row, LABEL_ALIAS),
    fields,
  };
}

/**
 * Values of one column for the rows the preview matched, used to seed the
 * cascade walk. Usually the referenced column is the primary key and the values
 * are already in hand; otherwise they are read back for the matched keys only.
 */
function rootValues(
  sql: Sql,
  relation: Relation,
  keyColumns: readonly string[],
  changes: readonly RowChange[],
): (column: string) => Promise<readonly string[]> {
  const cache = new Map<string, readonly string[]>();

  return async (column) => {
    const hit = cache.get(column);
    if (hit) return hit;

    let values: readonly string[];
    if (keyColumns.includes(column)) {
      values = [...new Set(changes.map((c) => keyValue(c, column)))];
    } else if (changes.length === 0) {
      values = [];
    } else {
      const rows = await sql(
        `SELECT DISTINCT ${quoteIdent(column)}::text AS v
           FROM ${qualify(relation.ref)}
          WHERE ${keyTuples(keyColumns, changes.length)}`,
        flatKeys(keyColumns, changes),
      );
      values = rows
        .map((row) => optionalText(row, "v"))
        .filter((value): value is string => value !== null);
    }
    cache.set(column, values);
    return values;
  };
}

function keyValue(change: RowChange, column: string): string {
  return required(change.key[column], `key column ${column}`);
}

function flatKeys(
  keyColumns: readonly string[],
  changes: readonly RowChange[],
): readonly string[] {
  return changes.flatMap((change) =>
    keyColumns.map((column) => keyValue(change, column)),
  );
}

/** `("k0"::text, "k1"::text) IN (($1, $2), ($3, $4))` */
function keyTuples(keyColumns: readonly string[], rowCount: number): string {
  const lhs = keyColumns.map((k) => `${quoteIdent(k)}::text`).join(", ");
  const tuples: string[] = [];
  let slot = 0;
  for (let row = 0; row < rowCount; row += 1) {
    tuples.push(`(${keyColumns.map(() => `$${(slot += 1)}`).join(", ")})`);
  }
  return `(${lhs}) IN (${tuples.join(", ")})`;
}

/**
 * Apply the previewed values, pinned to the previewed row versions.
 *
 * Every value crosses as text and is cast back with the column's catalog type,
 * so PostgreSQL's own input function reconstructs it. Keys and `xmin` compare as
 * text, which works for any key type without special cases.
 *
 * Column names go through `quoteIdent` and every value is a parameter, but the
 * cast target is a bare type name spliced into the statement, so it is checked
 * here as well as when the catalog produced it. A `Proposal` is plain JSON that
 * may have crossed a queue or a database row since, and this is the one field
 * on it that reaches SQL uninterpolated.
 */
function buildApply(proposal: Proposal): {
  text: string;
  params: readonly (string | null)[];
} {
  const { plan, table, changes, kind } = proposal;
  const keys = plan.keyColumns;
  const columns = plan.assignments;
  const perRow = keys.length + 1 + columns.length;

  const tupleColumns = [
    ...keys.map((_, i) => `k${i}`),
    "ver",
    ...columns.map((_, i) => `a${i}`),
  ];

  const tuples: string[] = [];
  const params: (string | null)[] = [];
  changes.forEach((change, rowIndex) => {
    const slots: string[] = [];
    for (let column = 0; column < perRow; column += 1) {
      slots.push(`$${rowIndex * perRow + column + 1}::text`);
    }
    tuples.push(`(${slots.join(", ")})`);

    for (const key of keys) params.push(keyValue(change, key));
    params.push(change.version);
    columns.forEach((_, i) => {
      // `after` may be SQL NULL; it must arrive as null, not "".
      params.push(required(change.fields[i], `field ${i}`).after);
    });
  });

  const values = `(VALUES ${tuples.join(", ")}) AS v(${tupleColumns.join(", ")})`;
  const match = [
    ...keys.map((key, i) => `t.${quoteIdent(key)}::text = v.k${i}`),
    "t.xmin::text = v.ver",
  ].join(" AND ");
  const returning = keys
    .map((key, i) => `t.${quoteIdent(key)}::text AS ${keyAlias(i)}`)
    .join(", ");

  if (kind === "delete") {
    return {
      text:
        `DELETE FROM ${qualify(table)} AS t USING ${values} ` +
        `WHERE ${match} RETURNING ${returning}`,
      params,
    };
  }

  const assignments = columns
    .map(
      (column, i) =>
        `${quoteIdent(column.column)} = v.a${i}::${assertTypeName(column.type)}`,
    )
    .join(", ");

  return {
    text:
      `UPDATE ${qualify(table)} AS t SET ${assignments} FROM ${values} ` +
      `WHERE ${match} RETURNING ${returning}`,
    params,
  };
}

/** Which previewed rows did not match, and what they look like now. */
async function findDrift(
  sql: Sql,
  proposal: Proposal,
  returned: readonly Row[],
): Promise<readonly DriftedRow[]> {
  const keys = proposal.plan.keyColumns;
  const identify = (values: readonly string[]): string => values.join(NUL);
  const rowIdentity = (row: Row): string =>
    identify(keys.map((_, i) => String(row[keyAlias(i)])));

  const applied = new Set(returned.map(rowIdentity));
  const missed = proposal.changes.filter(
    (change) => !applied.has(identify(keys.map((k) => keyValue(change, k)))),
  );
  if (missed.length === 0) return [];

  const current = await sql(
    `SELECT ${keys
      .map((key, i) => `${quoteIdent(key)}::text AS ${keyAlias(i)}`)
      .join(", ")}, xmin::text AS ${VERSION_ALIAS}
       FROM ${qualify(proposal.table)}
      WHERE ${keyTuples(keys, missed.length)}`,
    flatKeys(keys, missed),
  );

  const versions = new Map(
    current.map((row) => [rowIdentity(row), String(row[VERSION_ALIAS])]),
  );

  return missed.map((change) => {
    const identity = identify(keys.map((k) => keyValue(change, k)));
    const version = versions.get(identity);
    return {
      key: change.key,
      reason: version === undefined ? "missing" : "modified",
      currentVersion: version ?? null,
    };
  });
}
